# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Parameters(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.neurons = QtWidgets.QTabWidget(self.centralwidget)
        self.neurons.setToolTip("")
        self.neurons.setStatusTip("")
        self.neurons.setObjectName("neurons")
        self.neurons_tab = QtWidgets.QWidget()
        self.neurons_tab.setObjectName("neurons_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.neurons_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.neurons_widget = QtWidgets.QTableWidget(self.neurons_tab)
        self.neurons_widget.setRowCount(13)
        self.neurons_widget.setObjectName("neurons_widget")
        self.neurons_widget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.neurons_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.neurons_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.neurons_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.neurons_widget.setItem(12, 2, item)
        self.neurons_widget.horizontalHeader().setDefaultSectionSize(244)
        self.neurons_widget.horizontalHeader().setMinimumSectionSize(50)
        self.neurons_widget.verticalHeader().setVisible(False)
        self.neurons_widget.verticalHeader().setMinimumSectionSize(50)
        self.gridLayout.addWidget(self.neurons_widget, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.neurons.addTab(self.neurons_tab, "")
        self.topology_tab = QtWidgets.QWidget()
        self.topology_tab.setObjectName("topology_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.topology_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.topology_widget = QtWidgets.QTableWidget(self.topology_tab)
        self.topology_widget.setObjectName("topology_widget")
        self.topology_widget.setColumnCount(3)
        self.topology_widget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.topology_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.topology_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.topology_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.topology_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.topology_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.topology_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.topology_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.topology_widget.setHorizontalHeaderItem(2, item)
        self.topology_widget.horizontalHeader().setDefaultSectionSize(244)
        self.topology_widget.horizontalHeader().setMinimumSectionSize(50)
        self.topology_widget.verticalHeader().setVisible(False)
        self.topology_widget.verticalHeader().setMinimumSectionSize(50)
        self.gridLayout_4.addWidget(self.topology_widget, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.neurons.addTab(self.topology_tab, "")
        self.gridLayout_2.addWidget(self.neurons, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.neurons.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.neurons_widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.neurons_widget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.neurons_widget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.neurons_widget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.neurons_widget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.neurons_widget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.neurons_widget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.neurons_widget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.neurons_widget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.neurons_widget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.neurons_widget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.neurons_widget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.neurons_widget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.neurons_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Parameter Name"))
        item = self.neurons_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parameter Description"))
        item = self.neurons_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Parameter Value"))
        __sortingEnabled = self.neurons_widget.isSortingEnabled()
        self.neurons_widget.setSortingEnabled(False)
        item = self.neurons_widget.item(0, 0)
        item.setText(_translate("MainWindow", "Act_m"))
        item = self.neurons_widget.item(0, 1)
        item.setText(_translate("MainWindow", "Activation variable m"))
        item = self.neurons_widget.item(0, 2)
        item.setText(_translate("MainWindow", "0.05293248525725"))
        item = self.neurons_widget.item(1, 0)
        item.setText(_translate("MainWindow", "C_m"))
        item = self.neurons_widget.item(1, 1)
        item.setText(_translate("MainWindow", "Capacity of membrane (pF)"))
        item = self.neurons_widget.item(1, 2)
        item.setText(_translate("MainWindow", "100"))
        item = self.neurons_widget.item(2, 0)
        item.setText(_translate("MainWindow", "E_K"))
        item = self.neurons_widget.item(2, 1)
        item.setText(_translate("MainWindow", "Potassium reversal potential (mV)"))
        item = self.neurons_widget.item(2, 2)
        item.setText(_translate("MainWindow", "-77"))
        item = self.neurons_widget.item(3, 0)
        item.setText(_translate("MainWindow", "E_L"))
        item = self.neurons_widget.item(3, 1)
        item.setText(_translate("MainWindow", "Leak reversal potential"))
        item = self.neurons_widget.item(3, 2)
        item.setText(_translate("MainWindow", "-54.402"))
        item = self.neurons_widget.item(4, 0)
        item.setText(_translate("MainWindow", "E_Na"))
        item = self.neurons_widget.item(4, 1)
        item.setText(_translate("MainWindow", "Sodium reversal potential"))
        item = self.neurons_widget.item(4, 2)
        item.setText(_translate("MainWindow", "50"))
        item = self.neurons_widget.item(5, 0)
        item.setText(_translate("MainWindow", "g_K"))
        item = self.neurons_widget.item(5, 1)
        item.setText(_translate("MainWindow", "Potassium peak conductance (nS)"))
        item = self.neurons_widget.item(5, 2)
        item.setText(_translate("MainWindow", "3600"))
        item = self.neurons_widget.item(6, 0)
        item.setText(_translate("MainWindow", "g_L"))
        item = self.neurons_widget.item(6, 1)
        item.setText(_translate("MainWindow", "Leak conductance (nS)"))
        item = self.neurons_widget.item(6, 2)
        item.setText(_translate("MainWindow", "30"))
        item = self.neurons_widget.item(7, 0)
        item.setText(_translate("MainWindow", "g_Na"))
        item = self.neurons_widget.item(7, 1)
        item.setText(_translate("MainWindow", "Sodium peak conductance (nS)"))
        item = self.neurons_widget.item(7, 2)
        item.setText(_translate("MainWindow", "12000"))
        item = self.neurons_widget.item(8, 0)
        item.setText(_translate("MainWindow", "I_e"))
        item = self.neurons_widget.item(8, 1)
        item.setText(_translate("MainWindow", "External input current (pA)"))
        item = self.neurons_widget.item(8, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.neurons_widget.item(9, 0)
        item.setText(_translate("MainWindow", "Inact_n"))
        item = self.neurons_widget.item(9, 1)
        item.setText(_translate("MainWindow", "Inactivation variable m"))
        item = self.neurons_widget.item(9, 2)
        item.setText(_translate("MainWindow", "0.317676914060697"))
        item = self.neurons_widget.item(10, 0)
        item.setText(_translate("MainWindow", "model"))
        item = self.neurons_widget.item(10, 2)
        item.setText(_translate("MainWindow", "0.317676914060697"))
        item = self.neurons_widget.item(11, 0)
        item.setText(_translate("MainWindow", "type_id"))
        item = self.neurons_widget.item(11, 2)
        item.setText(_translate("MainWindow", "hh_psc_alpha"))
        item = self.neurons_widget.item(12, 0)
        item.setText(_translate("MainWindow", "V_m"))
        item = self.neurons_widget.item(12, 1)
        item.setText(_translate("MainWindow", "Membrane potential (mV)"))
        item = self.neurons_widget.item(12, 2)
        item.setText(_translate("MainWindow", "-65"))
        self.neurons_widget.setSortingEnabled(__sortingEnabled)
        self.neurons.setTabText(self.neurons.indexOf(self.neurons_tab), _translate("MainWindow", "Neurons"))
        item = self.topology_widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.topology_widget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.topology_widget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.topology_widget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.topology_widget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "6"))
        item = self.topology_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Connectivity"))
        item = self.topology_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Weight"))
        item = self.topology_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Delay"))
        self.neurons.setTabText(self.neurons.indexOf(self.topology_tab), _translate("MainWindow", "Network Topology"))

