# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stimuli_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Stimuli_Params(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stimuli_params = QtWidgets.QTableWidget(self.centralwidget)
        self.stimuli_params.setObjectName("stimuli_params")
        self.stimuli_params.setColumnCount(4)
        self.stimuli_params.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuli_params.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.stimuli_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.stimuli_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.stimuli_params.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.stimuli_params.setHorizontalHeaderItem(3, item)
        self.stimuli_params.horizontalHeader().setDefaultSectionSize(244)
        self.stimuli_params.horizontalHeader().setMinimumSectionSize(50)
        self.stimuli_params.verticalHeader().setVisible(False)
        self.stimuli_params.verticalHeader().setMinimumSectionSize(50)
        self.gridLayout.addWidget(self.stimuli_params, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stimuli Parameters"))
        item = self.stimuli_params.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.stimuli_params.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.stimuli_params.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.stimuli_params.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.stimuli_params.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.stimuli_params.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.stimuli_params.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.stimuli_params.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.stimuli_params.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.stimuli_params.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.stimuli_params.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Frequency"))
        item = self.stimuli_params.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Number of pulses"))
        item = self.stimuli_params.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.stimuli_params.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type of stimulation"))

